name: build games
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - master
    paths:
      - games/**
jobs:
  push:
    name: "games:source"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        game:
          - source
    steps:
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
          platforms: linux/amd64,linux/arm64
      - uses: docker/build-push-action@v4
        with:
          context: ./games/source
          file: ./games/source/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/rising-project/games:source
